variable "ami" {}
variable "count" {}
variable "tags" {}
variable "instance_type" {}
variable "key_name" {}
variable "security_groups" {}
variable "subnet_id" {}
variable "associate_public_ip_address" {}
variable "source_dest_check" {}
variable "team" {}