variable "vpc_zone_identifier" {}
variable "launch_configuration" {}
variable "cluster_name" {}
variable "min_size" {}
variable "max_size" {}      
variable "health_check_grace_period" {}
variable "health_check_type" {}
variable "force_delete" {}
variable "enabled_metrics" {}